### ISSUE TITLE
Some issues with examples

### ISSUE THREAD

**Issue by jonchengkuo** [Wissance/WebApiToolkit#2]
Hi Ushakov,

I like your WebApiToolkit. I found a few minor issues on the project home page (https://github.com/Wissance/WebApiToolkit):
1. In the Requirements section, "labrary" is misspelled.
2. In the GroupController example, the class constructor name is incorrect.
3. It'll be better if you can shown how the GroupEntity class implements IModelIdentifiable.

I also have the following comments on WebApiToolkit:
1. Base Controller: I personally think that passing the Manager object into the base controller via a constructor is easier to understand.
    i.e., public GroupController(GroupManager manager) : base(manager) { }
    
2. Order of type parameters is inconsistent between base controller and base manager.
    BasicReadController<**GroupDto, GroupEntity**, int>
    ModelManager<**GroupEntity, GroupDto**, int>

Joncheng

**Comment by EvilLord666** [comment]
@jonchengkuo , thank you for useful project review. I'll correct documentation asap and also i'll make example project without WebApiToolkit and with it. And also i will clarify order of base classes template paramters.  Thank you.

**Comment by EvilLord666** [comment]
@jonchengkuo , I've prepared a full example how to use (whole solution) you could check it here: https://github.com/Wissance/WeatherControl

**Comment by EvilLord666** [comment]
Readme updated using examples from link above

**Comment by EvilLord666** [comment]
Examples were updated and show full Controller && Manager clases, for reasonable notes created to issues: #6 , #7
